### ISSUE TITLE
Error: Failed to validate purchase if ['sandbox', 'production']

### ISSUE THREAD

**Issue by achirkof** [ladeiko/node-apple-receipt-verify#8]
```
........ /##### a lot of text with validated receipt info #####/............
I20180728-20:18:03.268(3)?   pending_renewal_info: 
I20180728-20:18:03.269(3)?    [ { expiration_intent: '1',
I20180728-20:18:03.269(3)?        auto_renew_product_id: 'com.smartfitness.smartworkout.autorenewable.1month',
I20180728-20:18:03.270(3)?        original_transaction_id: '1000000394103402',
I20180728-20:18:03.270(3)?        is_in_billing_retry_period: '0',
I20180728-20:18:03.270(3)?        product_id: 'com.xxxxxxxxxx.1month',
I20180728-20:18:03.271(3)?        auto_renew_status: '0' } ] }
I20180728-20:18:03.271(3)? <Apple> Try validate against production: https://buy.itunes.apple.com/verifyReceipt
I20180728-20:18:03.400(3)? <Apple> https://buy.itunes.apple.com/verifyReceipt validation response: { status: 21007 }
W20180728-20:18:03.413(3)? (STDERR) Error: failed to validate purchase
W20180728-20:18:03.414(3)? (STDERR)     at handleResponse (/home/smwk/develop/smartworkout-web/node_modules/node-apple-receipt-verify/lib/apple.js:430:6)
W20180728-20:18:03.414(3)? (STDERR)     at done (/home/smwk/develop/smartworkout-web/node_modules/node-apple-receipt-verify/lib/apple.js:220:5)
W20180728-20:18:03.415(3)? (STDERR)     at /home/smwk/develop/smartworkout-web/node_modules/node-apple-receipt-verify/node_modules/async/dist/async.js:3888:9
W20180728-20:18:03.415(3)? (STDERR)     at /home/smwk/develop/smartworkout-web/node_modules/node-apple-receipt-verify/node_modules/async/dist/async.js:473:16
W20180728-20:18:03.415(3)? (STDERR)     at replenish (/home/smwk/develop/smartworkout-web/node_modules/node-apple-receipt-verify/node_modules/async/dist/async.js:1006:25)
W20180728-20:18:03.416(3)? (STDERR)     at iterateeCallback (/home/smwk/develop/smartworkout-web/node_modules/node-apple-receipt-verify/node_modules/async/dist/async.js:995:17)
W20180728-20:18:03.416(3)? (STDERR)     at /home/smwk/develop/smartworkout-web/node_modules/node-apple-receipt-verify/node_modules/async/dist/async.js:969:16
W20180728-20:18:03.416(3)? (STDERR)     at /home/smwk/develop/smartworkout-web/node_modules/node-apple-receipt-verify/node_modules/async/dist/async.js:3885:13
W20180728-20:18:03.417(3)? (STDERR)     at /home/smwk/develop/smartworkout-web/node_modules/node-apple-receipt-verify/lib/apple.js:167:16
W20180728-20:18:03.417(3)? (STDERR)     at Request._callback (/home/smwk/develop/smartworkout-web/node_modules/node-apple-receipt-verify/lib/apple.js:441:12)
W20180728-20:18:03.417(3)? (STDERR)     at Request.self.callback (/home/smwk/develop/smartworkout-web/node_modules/request/request.js:185:22)
W20180728-20:18:03.418(3)? (STDERR)     at emitTwo (events.js:126:13)
W20180728-20:18:03.418(3)? (STDERR)     at Request.emit (events.js:214:7)
W20180728-20:18:03.418(3)? (STDERR)     at Request.<anonymous> (/home/smwk/develop/smartworkout-web/node_modules/request/request.js:1157:10)
W20180728-20:18:03.418(3)? (STDERR)     at emitOne (events.js:116:13)
W20180728-20:18:03.419(3)? (STDERR)     at Request.emit (events.js:211:7)
W20180728-20:18:03.419(3)? (STDERR)     at IncomingMessage.<anonymous> (/home/smwk/develop/smartworkout-web/node_modules/request/request.js:1079:12)
W20180728-20:18:03.419(3)? (STDERR)     at Object.onceWrapper (events.js:313:30)
W20180728-20:18:03.420(3)? (STDERR)     at emitNone (events.js:111:20)
W20180728-20:18:03.420(3)? (STDERR)     at IncomingMessage.emit (events.js:208:7)
W20180728-20:18:03.421(3)? (STDERR)     at endReadableNT (_stream_readable.js:1064:12)
W20180728-20:18:03.421(3)? (STDERR)     at _combinedTickCallback (internal/process/next_tick.js:138:11)
W20180728-20:18:03.421(3)? (STDERR)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
This is strange, because even though I got a receipt I also got an Error.

Here is my code:
```javascript
const appleReceiptVerify = require('node-apple-receipt-verify');
   appleReceiptVerify.config({
      secret: "#############################",
      environment: ['sandbox', 'production'],
         verbose: true            
   });         
                      
   var appleReceipt = this.bodyParams.receiptData;
   var promise = new Promise(function(resolve, reject) {
   appleReceiptVerify.validate({
      receipt: appleReceipt
   }, function (err, products) {
      if (err) {
         return console.error(err);
         reject(err);
      }
      console.log(products);
      resolve(products);
   });        
});
````

**Comment by ladeiko** [comment]
try:
   environment: ['production', 'sandbox'] 
instead of:
   environment: ['sandbox', 'production']

**Comment by achirkof** [comment]
Thanks! It's solves my issue.
